[package]
name = "nexa-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "=0.7.2", features = ["router"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
log = "0.4"
tracing = "0.1"
